name: google_books_repository
description: Shared Code between AngularDart and Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  http: ^0.13.4
  rxdart: ^0.27.5
