name: sharish
description: The social book library
version: 0.5.2+3
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.3
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^1.0.0-dev.2
  flutter_svg: ^1.1.4
  formz: ^0.4.0
  google_books_repository:
    path: packages/google_books_repository
  intl: ^0.18.0
  rxdart: ^0.27.5
  fluttertoast: ^8.1.2
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/PNG/
    - assets/images/SVG/
